### PR TITLE
Fix for RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### PR DESCRIPTION
**Pull request by xOIBrandon**
Fix for [Issue 549](https://github.com/gotev/android-upload-service/issues/549)

### CODE REVIEW

**Comment by xOIBrandon** [comment]
There are linter issues stoping CI. Running ktlint locally outputs a bunch of issues for files I didn't touch. I'm going to run `ktlint -F` and blindly accept the changes in a new commit.

**Comment by xOIBrandon** [comment]
I'm not sure why the android-test job is failing. I can't see any details on that here.

Running `./gradlew connectedCheck` locally all the tests are passing.

Screen Shot 2021-04-09 at 12 19 23 PM

Any suggestions?

**Comment by gotev** [comment]
Hi @xOIBrandon and thank you for this PR!

By looking at: https://github.com/gotev/android-upload-service/runs/2306229070 which is the first failed CI run:
```
> Task :uploadservice:ktlintMainSourceSetCheck
/home/runner/work/android-upload-service/android-upload-service/uploadservice/src/main/java/net/gotev/uploadservice/extensions/ContextExtensions.kt:6:1: Unused import
"plain" report written to /home/runner/work/android-upload-service/android-upload-service/uploadservice/build/reports/ktlint/ktlintMainSourceSetCheck.txt
```
The failure is caused by an unused import which is a consequence of [this modification](https://github.com/gotev/android-upload-service/pull/578/commits/4ab07c15b65bc3fc1de49a11cc8976e974203c89#diff-8b891e8bdbd07f985c9d073cfec5a80db70db013eb50dd851e08efee67519e3cR34). Simply removing that import would have fixed the build 😉 

From what I see we're using different ktlint versions. I'm still on 0.36.0 for many reasons. I would ask you to revert the auto format in this PR, to focus solely on the real changes and then we can proceed with further review 😉 

Thank you!

**Comment by gotev** [comment]
If you find it easier and faster, feel free to close this PR and open a new one starting from a clean state.

**Comment by gotev** [comment]
@xOIBrandon thank you! Since Google is not going to fix this, I think it's the best solution at the moment, at the cost of not being able to start an upload automatically when the app is in the background.

**Review by gotev — APPROVED** [review]

**Comment by xOIBrandon** [comment]
I didn't realize that was the implication of doing this 😐

Would moving over to WorkManager solve this?

**Comment by gotev** [comment]
@xOIBrandon got an idea: https://github.com/gotev/android-upload-service/pull/579

Moving to WorkManager is something I want to do in the next major release (#569), as it's the way forward. It's going to fix actual Service problems, but it will also add some additional dependencies which many of the current users may not want or dislike.

**Comment by xOIBrandon** [comment]
Very good idea!!

I bet it will significantly reduce the number of crashes in our app from this error.

**Pull request merged**
