### PR TITLE
SFTP upload module

### PR DESCRIPTION
**Pull request by mikepenz**
* add SFTP module (with the basic implementation as the FTP module)
* allows to do SFTP uploads (different then FTP / FTPS) using a username and password
* this implementation uses the JSch library: http://www.jcraft.com/jsch/
  * JSch has bsd license: http://www.jcraft.com/jsch/LICENSE.txt
* this PR solves the following issues:
  * https://github.com/gotev/android-upload-service/issues/280
  * https://github.com/gotev/android-upload-service/issues/199
  * https://github.com/gotev/android-upload-service/issues/112 (second part)

--------------

@gotev

### CODE REVIEW

**Comment by mikepenz** [comment]
Ok found a problem in my project with the upload. will address it and update the PR afterwards

**Comment by mikepenz** [comment]
Ok found and fixed it :)

**Comment by gotev** [comment]
Hi @mikepenz and thank you for this PR 🚀 It's pending from a really long time and it will need a refresh, because I didn't have time to review it until now. Great job and this can be merged 👌

Is this a feature you are still using in production and which are you wanting to maintain? Unfortunately I can't do it, but you can become a maintainer of the library if you accept.

It's out of scope, but it's great to see your name here, since I got inspiration from your [FastAdapter](https://github.com/mikepenz/FastAdapter) to make my [RecyclerAdapter](https://github.com/gotev/recycler-adapter) library. It does a fraction of the things yours does, but it's all I need. Thank you for that, too!

**Comment by mikepenz** [comment]
@gotev hey. No worries. I know how it is if there's not enough time for everything :D 

Sadly it is no longer used in production. As such it will be hard for me to maintain it further. 
Thank you so much for the offer, I really appreciate this. But I guess as the addon is no longer used in production I won't be of too much help I believe. :D 

Really happy to hear that. It is always great to see that some of the open source work I did, inspired others too. 

Great work on your libraries too! Keep going ;)

**Comment by gotev** [comment]
@mikepenz what a pity! I comprehend the burden of maintaining something you are not using anymore in production, so I think the better thing to do it to close this PR and don't merge it. Keep going on your libraries too! 😎

If someone else wants to take the lead and maintain it, just contact me and let's talk about it.

**Comment by mikepenz** [comment]
Yes makes absolute sense :). It would just cost time to maintain, Not sure if the issues related to this PR were still relevant. 
In the worst case the PR can still be found and if somebody needs it can cherry pick over :P

**Pull request closed without merging**
