### PR TITLE
chunk upload feature

### PR DESCRIPTION
**Pull request by alez007**
I needed a chunk upload feature for binary upload and it works fine so far, the main idea is to set a CHUNK_SIZE (default is 5MB) at initialisation and .setChunkUpload(true) in the BinaryUploadRequest request.

### CODE REVIEW

**Comment by alez007** [comment]
I'm also aiming to implement a way to resume this upload, let me know if you're having any problems with this feature. Have fun!

**Comment by gotev** [comment]
@alez007 thanks for the PR! I'm working on something similar, but also with resume capabilities for the next release. My implementation is different from the one you proposed, so I'm not going to directly merge your code, but I'll use some of your ideas, so I will add you to the contributors as well with credits for the snippets of your code.

**Comment by Robertoq7** [comment]
Hi @gotev !

> I'm working on something similar, but also with resume capabilities for the next release. 

Can you tell me please when will be avaliable this release? 

Thank you,
Robert

**Comment by gotev** [comment]
@Robertoq7 just follow the project issues and this thread. There's no time estimate 😃

**Comment by gotev** [comment]
@alez007 have you managed to support resuming the uploads? I started looking your code. Are you using it for S3 or other cloud storage service?

**Comment by alez007** [comment]
@gotev I'm currently using it for an in-house resume upload feature that needs chunks uploaded in order.  Regarding S3, I haven't used it with multipart upload although that would make for a nice exercise, I can give that a try if you're not in a hurry :). I haven't had too much time lately and I kind of pulled all master changes into my repo and solved conflicts, but I saw quite a few structural changes were made.

**Comment by gotev** [comment]
What I want is to join our ideas and add a good chunk upload feature with resume capability, which can be pluginnable, to support for example S3, Google Drive and Tus, which is an open source protocol for uploading, so your custom upload feature can be seen as a plugin and you will also have easier maintenance over time.

If necessary, we can also change the current architecture if it doesn't fit. The goal is to have reliable resumable uploads on Android and easy to maintain codebase.

I'm not in a hurry :smiley:

**Comment by DanielNovak** [comment]
@alez007 is the chunk upload code working fine for you? Is the PR still valid (code is up-to-date)? We need to support chunk upload and your PR could be very helpful until the official library supports it.  Thanks.

**Comment by alez007** [comment]
@DanielNovak yes, using it in production. It's a simple fix for the current pull request that is failing tests, if I have time later on I'll push a working code.

**Comment by DanielNovak** [comment]
@alez007 Thanks, and did you figure out how to resume the upload (I understand that this is not part of the PR). Basically what I want to support is resume in case the connection drops out and you are uploading a large file.

**Comment by alez007** [comment]
A proper resume feature will involve a bit more work, currently the resume capability will have to be done on your side, my resume capability is based on onChunkUploadSuccess event, I'm saving the status of what has been uploaded so far somewhere in the app

**Comment by DanielNovak** [comment]
Thank you again. I will try to implement something similar in our project - it seems like this should be the easier part (just storing the upload progress somewhere in the DB, and then using this when the upload is restarted).

**Comment by alez007** [comment]
I think it's ready to be used as it is, I've also updated the branch with latest commits from master. The build fails with a strange error, `error: package NotificationCompat does not exist` but it should work once you import it into your project.

**Comment by gotev** [comment]
A resumable upload protocol is needed for resume capabilities to work. Thought about adding support for the open source tus protocol, but I need help since I don't have much time to do it myself. I'll be glad to assist the implementation though.

**Comment by DanielNovak** [comment]
@gotev I am waiting for the info from our backend guys - since we are just starting a new project and I am doing research for the Android part. I am sure they will probably pick the simpler approach - sending files in chunks (TUS seems to be more complicated). So I will report back later and I will try to submit a PR if I have something to share, but right now this PR may cover my needs (in case we go with chunked mode).

**Comment by alez007** [comment]
@gotev clearly this kind of request is going to return from time to time, I'll see if I can find some time to at least start it

**Comment by ubuntudroid** [comment]
Any news on chunk uploads?

**Comment by gotev** [comment]
As announced, I'm closing this

**Pull request closed without merging**
