### PR TITLE
S3 Upload

### PR DESCRIPTION
**Pull request by Borna-f**
Remaining Items:
- Unit Tests

### CODE REVIEW

**Comment by gotev** [comment]
Wow great!! Given a quick look at what you committed. S3 implementation should be moved in its own module, like ftp for example, as it relies on external libraries and needs specific S3 implementations.

**Comment by Borna-f** [comment]
@gotev Hi,
Thanks for your feedback. I fixed that. However, I don't know how to resume download on network disconnect, upload failure, etc. I was expecting the UploadRequest would handle that automatically based on Retry policy but that is simply not the case. I tried throwing exception on upload failure but it causes the app crash. Any suggestion or help would be appreciated. Thanks.

**Comment by gotev** [comment]
@Borna-f upload service does not detect internet connectivity status and the retry policy provides a mechanism to retry a failed task after some time. After all the retries are done and you still have errors, the task fails permanently and the library user has to re-schedule the task to run again.

When you are implementing the upload task think this way:
- when implementing a resumable protocol, is there a previous status for this upload which I can restore to resume from where I left?
- perform the actual upload
- when implementing a resumable protocol, save the successful increment states persistently, so it's possible to resume status later

Let me know if you need further information or guidance. I'm open to suggestions and improvements to the library core.

**Comment by Borna-f** [comment]
@gotev Thanks for your response. The thing I cannot understand is the mechanism of the retry. Let's say there is any sort of error, how do we inform the upload service about this error? I mean if there would have been some sort of onResponseReceived(ServerResponse.successfulEmpty()) but for failure that would have been great. And then the upload service would retry for example in an incident of error.

Also for the cancel mechanism, when I do cancel and implement the cancel methods appropriate to S3 how can we set the notification to cancel state? I see that it happens in all your methods (FTP for example) but I cannot understand how. I can stop the upload but I don't know how to change the notification to "user cancelled upload."

By the way I think it might be better if possible to set the params.file.successfullyUploaded = true on onResponseReceived(ServerResponse.successfulEmpty()) function. S3 has it's own threading mechanism and observer and when I want to access the files on the observer onCompleted I don't have access to params.files there.

Thank you

**Comment by gotev** [comment]
@Borna-f the whole upload and retry mechanism is implemented here:

https://github.com/gotev/android-upload-service/blob/ff518f03159c5b1e7b2b001c75d26fbcc22c542a/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.kt#L131-L173

This is the method which calls your implementation's `upload` method. When `upload` throws an exception which is not handled in your code, it counts as a failed attempt.

The cancel mechanism is based on this flag:

https://github.com/gotev/android-upload-service/blob/ff518f03159c5b1e7b2b001c75d26fbcc22c542a/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.kt#L31-L40

which is used and checked at various steps (to get a complete overview and working examples, search for `shouldContinue` in the codebase). Both Binary and Multipart uploads (which extends HttpUploadTask) are using the HttpStack abstraction implemented in Upload Service, which allows to decouple upload code from the stack used underneath (so you can use HttpUrlConnection or OkHttp or another stack) and which has support for cancellation on demand logic.

For example, in Multipart upload, this is the method used to upload a file:

https://github.com/gotev/android-upload-service/blob/ff518f03159c5b1e7b2b001c75d26fbcc22c542a/uploadservice/src/main/java/net/gotev/uploadservice/network/BodyWriter.kt#L27-L45

The key here is `listener.shouldContinueWriting()` which gets checked internally by the HttpStack abstraction. In HttpUploadTask you'll find also:

https://github.com/gotev/android-upload-service/blob/ff518f03159c5b1e7b2b001c75d26fbcc22c542a/uploadservice/src/main/java/net/gotev/uploadservice/HttpUploadTask.kt#L70

which links the `shouldContinue`  to the HttpStack internal cancellation mechanism.

> S3 has it's own threading mechanism and observer and when I want to access the files on the observer onCompleted I don't have access to params.files there.

One of the founding ideas when I made this library is that I want to decouple upload implementations from external libraries, so you could use a single Http Stack of choice in your app and just plug it in Upload Service and be free to change it later without reimplementing upload logic. For this to happen I made the HttpStack abstraction, used in Binary and Multipart. FTP is a completely different protocol, so in that case I wrapped an external library.

Regarding S3, the APIs underneath are a combination of Http Calls. AWS libs allows to save some time initially by providing a convenient interface, but you have to play by their rules then. I don't have the knowledge of their internal threading mechanisms and lifecycle to suggest you a possible way to implement request cancellation.

IMHO, the best way to implement S3 protocol and support all the upload service native features (like switching http stack for example to name one) without resorting to hacks or workarounds is to start from here: https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html and implement the calls using the HttpStack abstraction, but I understand it takes much longer initially than to use their libraries and just wrap them. I also understand and I'm aware `HttpStack` is not perfect and could be improved, but that's one of the reasons I made this open source. Great stuff happens when many people adds their bit.

**Comment by Borna-f** [comment]
@gotev Thanks for your detailed response. I finally managed to make it working fully. Feel free to start reviewing. I had to change some of the base classes (UploadTask, and serverResponse) but it won't affect anything in terms of functionality.

This PR, doesn't have the unit tests yet. Perhaps that's why it's failing the build? Other than that let me know if you have any comments on the code. Hopefully if we can make it available to the public to use that would be nice.

Thanks

**Comment by gotev** [comment]
@Borna-f First of all, thank you for this PR 🎉 

Starting from the CI, please inspect the details provided in the GitHub Actions logs and fix the issues reported, because as I see some of your modifications in `UploadTask` have introduced regressions in the existing retry mechanism. I also need explanations about the modifications made inside `UploadTask` and the reasons behind them.

Before going on further with the review, which I'm really glad to make to give you some feedbacks, I have to tackle the ownership & maintenance stuff. I don't have the required time to take ownership of the maintenance and evolution of this plugin and support users about specific S3 matters which may arise. My goal is to maintain and evolve the core and to allow third party integrations like this to be done easily, leveraging the built-in features. I'm interested to know what you found easy, what you found confusing and what you thought to be improvable.

Upload Service is designed to be plugin-able on purpose, to allow also third party integrations like this, but for the plugin to be developed and distributed to the public, it's not necessary to be in this codebase. In fact, what I suggest you is to maintain full ownership of the plugin in your GitHub repo and distribute it like you find it convenient (e.g. JitPack, Maven Central, Jcenter). I'm more than happy to give feedbacks, reviews and to provide guidance like I've done so far for improvements. I can also add links to your implementation in the library main README and Wiki pages, to allow other users to easily discover and use your implementation.

From the current state in which you are now, to a fully independent codebase with a dependency on the core, there are some easy steps:
- remove `uploadservice` and `uploadservice-ftp` modules and leave only your own `uploadservice-s3` module with the demo app, in which you may then showcase your specific S3 features to potential users. 
- Feel also free to drop the demo app completely and rewrite it from scratch if that's more convenient and easy for you than refactoring the existing one
- modify the dependency of your module to be [like described here](https://github.com/gotev/android-upload-service/wiki/Getting-Started-with-4.x#setup). In this way you will depend on the specific core version you choose
- change the package name and groupId of your module to `com.yourcompany`
- change the README to showcase only your plugin features (you can use the FTP module readme as an example)

Then, to deploy the plugin, if you are also using jCenter like me, you can leverage the existing `release` script. Just add the following to your root `local.properties`:
```
bintray.apikey=yourapikey
bintray.user=yourusername
```
and you're good to go.

Before going on, I need your feedback on the above and then we can do the next steps together 😉

**Comment by Borna-f** [comment]
@gotev Thanks for making the fix for gradle so quickly.
I am having issues importing my newly added library via jitpack. It imports everything (ftp, uploadservice, etc.) but my new S3upload. When I tried to decompile the jar file I've got

Manifest-Version: 1.0
Built-By: jitpack
Description: Auto-generated artifact that depends on modules: uploadservice, uploadservice-ftp, uploadservice-okhttp

So S3 is not there. Is there any considerations I should take for importing the added library?

Thanks

**Comment by gotev** [comment]
@Borna-f try reporting the issue to JitPack directly

**Comment by gotev** [comment]
For the reasons explained [here](https://github.com/gotev/android-upload-service/pull/541#issuecomment-738466784) and lack of further feedback about open questions in the last month, I'm closing this PR.

**Pull request closed without merging**
